name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master, feature/wasm-github-pages ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    
    - name: Configure git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch main
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    
    - name: Install wasm-bindgen-cli
      run: cargo install wasm-bindgen-cli
    
    - name: Install wasm-opt
      run: cargo install wasm-opt
    
    - name: Build WASM
      run: cargo build --profile wasm-release --target wasm32-unknown-unknown
    
    - name: Optimize WASM
      run: wasm-opt -Oz --output www/brain_notes.wasm target/wasm32-unknown-unknown/wasm-release/guitar-notes.wasm
    
    - name: Bindgen
      run: wasm-bindgen --out-name brain_notes --out-dir www --target web target/wasm32-unknown-unknown/wasm-release/guitar-notes.wasm
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./www
        enable_jekyll: false
        force_orphan: true