name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master, feature/wasm-github-pages ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    
    - name: Prepare
      run: |
        cargo install wasm-bindgen-cli
        cargo install wasm-opt
    
    - name: Build WASM
      run: |
        source "$HOME/.cargo/env"
        cargo build --profile wasm-release --target wasm32-unknown-unknown
    
    - name: Optimize WASM
      run: |
        wasm-opt -Oz --output optimized.wasm target/wasm32-unknown-unknown/wasm-release/guitar-notes.wasm
        mv optimized.wasm target/wasm32-unknown-unknown/wasm-release/guitar-notes.wasm
    
    - name: Bindgen
      run: |
        wasm-bindgen --out-name guitar_notes --out-dir www --target web target/wasm32-unknown-unknown/wasm-release/guitar-notes.wasm
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./www
